"""Member 5: five clean document templates + PDF generation.

The templates are drafts for user review. They do not claim to be court forms,
registered instruments, or legal advice. The caller can import `generate_pdf` and
`TEMPLATES` into the main FastAPI application.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path
import re

from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib import colors

ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = ROOT / "generated_documents"
OUTPUT_DIR.mkdir(exist_ok=True)

DISCLAIMER = (
    "Draft generated by Asaan Qanoon AI for informational/document-preparation use. "
    "Review all facts, dates, amounts and legal requirements before signing or submitting. "
    "This draft is not legal advice and is not a substitute for a lawyer or competent authority."
)

TEMPLATES = {
    "loss_affidavit": {
        "title": "Loss Affidavit",
        "fields": ["full_name", "father_name", "cnic", "address", "lost_document", "loss_date", "loss_place", "purpose"],
    },
    "undertaking": {
        "title": "Undertaking",
        "fields": ["full_name", "father_name", "cnic", "address", "subject", "undertaking_text", "date"],
    },
    "general_application": {
        "title": "General Application",
        "fields": ["applicant_name", "cnic", "address", "authority", "subject", "body", "date"],
    },
    "complaint_letter": {
        "title": "Complaint Letter",
        "fields": ["complainant_name", "cnic", "address", "authority", "subject", "incident", "requested_action", "date"],
    },
    "rent_agreement": {
        "title": "Basic Rent Agreement Draft",
        "fields": ["landlord_name", "tenant_name", "landlord_cnic", "tenant_cnic", "property_address", "monthly_rent", "security_deposit", "start_date", "end_date", "province", "special_terms", "date"],
    },
}


def _safe_filename(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip()).strip("-")
    return value[:60] or "document"


def validate(template: str, data: dict) -> list[str]:
    if template not in TEMPLATES:
        raise ValueError(f"Unknown template: {template}")
    missing = []
    for field in TEMPLATES[template]["fields"]:
        value = str(data.get(field, "")).strip()
        if not value:
            missing.append(field)
    return missing


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("DocTitle", parent=base["Title"], alignment=TA_CENTER, fontSize=16, leading=20, spaceAfter=10),
        "heading": ParagraphStyle("Heading", parent=base["Heading2"], fontSize=11, leading=14, spaceBefore=8, spaceAfter=5),
        "body": ParagraphStyle("Body", parent=base["BodyText"], fontSize=9.5, leading=14, spaceAfter=6),
        "small": ParagraphStyle("Small", parent=base["BodyText"], fontSize=7.5, leading=10),
        "center": ParagraphStyle("Center", parent=base["BodyText"], alignment=TA_CENTER, fontSize=9.5, leading=13),
    }


def _p(text: str, style) -> Paragraph:
    safe = str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return Paragraph(safe.replace("\n", "<br/>"), style)


def _signature_table(style):
    return Table(
        [[_p("Applicant / Party Signature", style), _p("Date", style)], ["", ""], ["____________________________", "________________"]],
        colWidths=[105 * mm, 65 * mm],
        rowHeights=[10 * mm, 12 * mm, 10 * mm],
        style=TableStyle([("GRID", (0, 0), (-1, -1), 0.4, colors.grey), ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]),
    )


def build_story(template: str, data: dict) -> list:
    styles = _styles()
    story = [_p(TEMPLATES[template]["title"], styles["title"])]

    if template == "loss_affidavit":
        story += [
            _p(f"I, {data['full_name']}, son/daughter of {data['father_name']}, CNIC {data['cnic']}, resident of {data['address']}, state that the following document was lost: {data['lost_document']}.", styles["body"]),
            _p(f"Date of loss: {data['loss_date']}<br/>Place of loss: {data['loss_place']}", styles["body"]),
            _p(f"Purpose of this declaration: {data['purpose']}", styles["body"]),
            _p("I declare that the information stated above is true to the best of my knowledge. I understand that this draft must be reviewed for any oath, attestation, stamp-paper or authority-specific requirement before use.", styles["body"]),
            Spacer(1, 8), _signature_table(styles["body"]),
        ]

    elif template == "undertaking":
        story += [
            _p(f"I, {data['full_name']}, son/daughter of {data['father_name']}, CNIC {data['cnic']}, resident of {data['address']}, submit this undertaking regarding: {data['subject']}.", styles["body"]),
            _p(data["undertaking_text"], styles["body"]),
            _p("I confirm that the information provided by me is accurate to the best of my knowledge and that I will comply with the applicable requirements of the receiving authority.", styles["body"]),
            Spacer(1, 8), _signature_table(styles["body"]),
        ]

    elif template == "general_application":
        story += [
            _p(f"To:<br/>{data['authority']}", styles["body"]),
            _p(f"Subject: {data['subject']}", styles["heading"]),
            _p(f"Respected Sir/Madam,\n\n{data['body']}", styles["body"]),
            _p(f"Applicant: {data['applicant_name']}<br/>CNIC: {data['cnic']}<br/>Address: {data['address']}<br/>Date: {data['date']}", styles["body"]),
            Spacer(1, 8), _signature_table(styles["body"]),
        ]

    elif template == "complaint_letter":
        story += [
            _p(f"To:<br/>{data['authority']}", styles["body"]),
            _p(f"Subject: {data['subject']}", styles["heading"]),
            _p(f"Complainant: {data['complainant_name']}<br/>CNIC: {data['cnic']}<br/>Address: {data['address']}", styles["body"]),
            _p(f"Incident / complaint details:\n{data['incident']}", styles["body"]),
            _p(f"Requested action:\n{data['requested_action']}", styles["body"]),
            _p(f"Date: {data['date']}", styles["body"]),
            Spacer(1, 8), _signature_table(styles["body"]),
        ]

    elif template == "rent_agreement":
        story += [
            _p("Basic residential rent agreement draft. The applicable provincial law and any registration/stamping requirements must be checked before execution.", styles["small"]),
            _p(f"Landlord: {data['landlord_name']} (CNIC: {data['landlord_cnic']})<br/>Tenant: {data['tenant_name']} (CNIC: {data['tenant_cnic']})<br/>Property: {data['property_address']}<br/>Province/territory: {data['province']}", styles["body"]),
            _p(f"Monthly rent: {data['monthly_rent']}<br/>Security deposit: {data['security_deposit']}<br/>Start date: {data['start_date']}<br/>End date: {data['end_date']}", styles["body"]),
            _p("Agreed terms", styles["heading"]),
            _p(data["special_terms"], styles["body"]),
            _p("The parties should confirm applicable tenancy law, notice rules, stamping/registration requirements, and dispute-resolution procedure for the property's location before signing.", styles["body"]),
            Spacer(1, 8),
            Table(
                [[_p("Landlord signature", styles["center"]), _p("Tenant signature", styles["center"])], ["", ""], ["____________________________", "____________________________"]],
                colWidths=[85 * mm, 85 * mm], rowHeights=[10 * mm, 12 * mm, 10 * mm],
                style=TableStyle([("GRID", (0, 0), (-1, -1), 0.4, colors.grey), ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]),
            ),
        ]

    story += [Spacer(1, 12), _p(DISCLAIMER, styles["small"]), _p(f"Generated: {date.today().isoformat()}", styles["small"])]
    return story


def generate_pdf(template: str, data: dict, output_dir: str | Path | None = None) -> Path:
    missing = validate(template, data)
    if missing:
        raise ValueError("Missing required fields: " + ", ".join(missing))

    target_dir = Path(output_dir) if output_dir else OUTPUT_DIR
    target_dir.mkdir(parents=True, exist_ok=True)
    name = _safe_filename(f"asaan-qanoon-{template}-{data.get('full_name') or data.get('applicant_name') or data.get('tenant_name')}")
    path = target_dir / f"{name}.pdf"

    doc = SimpleDocTemplate(str(path), pagesize=A4, rightMargin=18 * mm, leftMargin=18 * mm, topMargin=18 * mm, bottomMargin=18 * mm)
    doc.build(build_story(template, data))
    return path


def list_templates() -> list[dict]:
    return [{"id": key, "title": value["title"], "fields": value["fields"]} for key, value in TEMPLATES.items()]
